package com.epam.tsylko.andrei.controller;


public enum CommandName {
    SIGN_IN,
    WRONG_REQUEST,
    ADD_BOOK,
    SHOW_ALL_BOOKS,
    EDIT_BOOK,
    GET_BOOK,
    BOOK_AVAILABILITY_STATUS,
    HOME_ADDRESS,
    EDIT_ADDRESS,
    CURRENT_ADDRESS,
    USER_REGISTRATION,
    USER_EDITED,
    ALL_USERS,
    GET_USER,
    USER_ROLE,
    USER_STATUS
    ,BOOK_RESERVATION,
    CANCELLATION_BOOK_RESERVATION,
    BOOK_LEAVED_LIBRARY,
    BOOK_RETURNED_COMMAND,
    REDUCE_ACCESS_LEVEL_COMMAND,
    SORTED_BOOKS
}
